// Code generated by go-dbmodel-gen. DO NOT EDIT.
// versions:
// 	go-dbmodel-gen v1.0.2
// nolint
package model

import (
    "time"
    "fmt"

	"ginTemplate/model/common"
)

/** JSGEN({type: "model", paged: true})
CREATE TABLE tbBlogLike (
    id int(10) NOT NULL AUTO_INCREMENT  COMMENT 'ID',
    blogId int(10) NOT NULL COMMENT '博客Id',
    uId int(10) NOT NULL COMMENT '用户Id',
    status int(10) NOT NULL DEFAULT 1 COMMENT '记录状态：1表示可用，0表示不可用',
    creator varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
    createTime datetime NOT NULL COMMENT '创建时间@now',
    updater varchar(64) NOT NULL DEFAULT '' COMMENT '最后更新人',
    updateTime datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (id)
);
JSGEN **/

var _ = time.Now

// BlogLikeConnection BlogLike连接类型
type BlogLikeConnection func() common.DBConnect

// DefaultBlogLikeConnection DefaultBlogLike默认连接
var DefaultBlogLikeConnection BlogLikeConnection

// BlogLike BlogLike值类型
type BlogLike struct {
  ID int `json:"id"`
  BlogID int `json:"blogId"`
  UID int `json:"uId"`
  Status int `json:"status"`
  Creator string `json:"creator"`
  CreateTime time.Time `json:"createTime"`
  Updater string `json:"updater"`
  UpdateTime time.Time `json:"updateTime"`
}

// Add 插入BlogLike
func (c BlogLikeConnection) Add(model *BlogLike) (int64, error) {
    sqlStr := "INSERT INTO `tbBlogLike` (`blogId`, `uId`, `status`, `creator`, `createTime`, `updater`) VALUES(?, ?, ?, ?, now(), ?)"
    result, err := c().Exec(sqlStr, model.BlogID, model.UID, model.Status, model.Creator, model.Updater)
    if err != nil {
        return 0, err
    } 
    
    return result.LastInsertId()
}

// AddBlogLike 插入BlogLike
func AddBlogLike(model *BlogLike) (int64, error) {
    return DefaultBlogLikeConnection.Add(model)
}

// Find 查询BlogLike
func (c BlogLikeConnection) Find(condition string, args ...interface{}) ([]*BlogLike, error) {
    sqlStr := "SELECT `id`, `blogId`, `uId`, `status`, `creator`, `createTime`, `updater`, `updateTime` FROM `tbBlogLike`"
    if len(condition) > 0 {
        sqlStr = sqlStr + " WHERE " + condition
    }
    results := make([]*BlogLike, 0)

	stmt, err := c().Prepare(sqlStr)
	if err != nil {
		return results, err
	}
	defer stmt.Close()
	rows, err := stmt.Query(args...)
    if err != nil {
        return results, err
    } 
    
        defer rows.Close()
        for rows.Next() {
            model := BlogLike{}
            values := []interface{}{
              new(interface{}),
              new(interface{}),
              new(interface{}),
              new(interface{}),
              new(interface{}),
              new(interface{}),
              new(interface{}),
              new(interface{}),
            }
            rows.Scan(values...)
            if *(values[0].(*interface{})) != nil {
                tmp := int((*(values[0].(*interface{}))).(int64))
                model.ID = tmp
            }
            if *(values[1].(*interface{})) != nil {
                tmp := int((*(values[1].(*interface{}))).(int64))
                model.BlogID = tmp
            }
            if *(values[2].(*interface{})) != nil {
                tmp := int((*(values[2].(*interface{}))).(int64))
                model.UID = tmp
            }
            if *(values[3].(*interface{})) != nil {
                tmp := int((*(values[3].(*interface{}))).(int64))
                model.Status = tmp
            }
            if *(values[4].(*interface{})) != nil {
                tmp := string((*(values[4].(*interface{}))).([]uint8))
                model.Creator = tmp
            }
            if *(values[5].(*interface{})) != nil {
                tmp := (*(values[5].(*interface{}))).(time.Time)
                model.CreateTime = tmp
            }
            if *(values[6].(*interface{})) != nil {
                tmp := string((*(values[6].(*interface{}))).([]uint8))
                model.Updater = tmp
            }
            if *(values[7].(*interface{})) != nil {
                tmp := (*(values[7].(*interface{}))).(time.Time)
                model.UpdateTime = tmp
            }
            results = append(results, &model)
        }
    return results, nil
}

// FindBlogLike 查询BlogLike
func FindBlogLike(condition string, args ...interface{}) ([]*BlogLike, error) {
    return DefaultBlogLikeConnection.Find(condition, args...)
}
// PagedQuery 分页查询BlogLike
func (c BlogLikeConnection) PagedQuery(condition string, pageSize uint, page uint, args ...interface{}) (totalCount uint, rows []*BlogLike, err error) {
	sqlStr := "SELECT COUNT(1) as cnt FROM `tbBlogLike`"
	if len(condition) > 0 {
		sqlStr = sqlStr + " WHERE " + condition
	}

	cr := c().QueryRow(sqlStr, args...)

	err = cr.Scan(&totalCount)
	if err != nil {
		return 0, nil, err
	}
	if page > 0 {
		page = page - 1
	}
	offset := page * pageSize
	if totalCount <= offset {
		return totalCount, []*BlogLike{}, nil
	}

	if len(condition) == 0 {
		condition = fmt.Sprintf("1=1")
	}
	condition = condition + fmt.Sprintf(" LIMIT %d OFFSET %d", pageSize, offset)
	rows, err = c.Find(condition, args...)
	return
}

// BlogLikePagedQuery 分页查询BlogLike
func BlogLikePagedQuery(condition string, pageSize uint, page uint, args ...interface{}) (totalCount uint, rows []*BlogLike, err error) {
	return DefaultBlogLikeConnection.PagedQuery(condition, pageSize, page, args...)
}

// Get 获取BlogLike
func (c BlogLikeConnection) Get(condition string, args ...interface{}) (*BlogLike, error) {
    results, err := c.Find(condition, args...)

    if err != nil {
        return nil, err
    } 
    
    if len(results) > 0 {
        return results[0], nil
    } 
        
    return nil, nil
}


// GetBlogLike 获取BlogLike
func GetBlogLike(condition string, args ...interface{}) (*BlogLike, error) {
    return DefaultBlogLikeConnection.Get(condition, args...)
}

// Update 更新BlogLike
func (c BlogLikeConnection) Update(model *BlogLike) (int64, error) {
    sqlStr := "UPDATE `tbBlogLike` SET `blogId` = ?, `uId` = ?, `status` = ?, `creator` = ?, `updater` = ? WHERE `id` = ?"
    result, err := c().Exec(sqlStr, model.BlogID, model.UID, model.Status, model.Creator, model.Updater, model.ID)
    if err != nil {
        return 0, err
    }
    return result.RowsAffected()
}

// UpdateBlogLike 更新BlogLike
func UpdateBlogLike(model *BlogLike) (int64, error) {
    return DefaultBlogLikeConnection.Update(model)
}
